/*
 *  message.c - Ant::Message class
 *  $Id$
 *
 *  Authors:
 *    * Michael Granger <ged@FaerieMUD.org>
 *
 */

#include "ant_ext.h"

VALUE rant_cAntMessage;




void
init_ant_message()
{

#ifdef FOR_RDOC
	rb_cData = rb_define_class( "Data" );
	rant_mAnt = rb_define_module( "Ant" );
#endif

	rant_cAntMessage = rb_define_class_under( rant_mAnt, "Message", rb_cObject );

#define EXPOSE_CONST( name ) \
	rb_define_const( rant_cAntMessage, #name, INT2FIX( (name) ) )

	EXPOSE_CONST( MESG_TX_SYNC );
	EXPOSE_CONST( MESG_RX_SYNC );
	EXPOSE_CONST( MESG_SYNC_SIZE );
	EXPOSE_CONST( MESG_SIZE_SIZE );
	EXPOSE_CONST( MESG_ID_SIZE );
	EXPOSE_CONST( MESG_CHANNEL_NUM_SIZE );
	EXPOSE_CONST( MESG_EXT_MESG_BF_SIZE );
	EXPOSE_CONST( MESG_CHECKSUM_SIZE );
	EXPOSE_CONST( MESG_DATA_SIZE );

	EXPOSE_CONST( MESG_ANT_MAX_PAYLOAD_SIZE );

	EXPOSE_CONST( MESG_MAX_EXT_DATA_SIZE );

	EXPOSE_CONST( MESG_MAX_DATA_SIZE );
	EXPOSE_CONST( MESG_MAX_SIZE_VALUE );
	EXPOSE_CONST( MESG_BUFFER_SIZE );
	EXPOSE_CONST( MESG_FRAMED_SIZE );
	EXPOSE_CONST( MESG_HEADER_SIZE );
	EXPOSE_CONST( MESG_FRAME_SIZE );
	EXPOSE_CONST( MESG_MAX_SIZE );

	EXPOSE_CONST( MESG_SIZE_OFFSET );
	EXPOSE_CONST( MESG_ID_OFFSET );
	EXPOSE_CONST( MESG_DATA_OFFSET );
	EXPOSE_CONST( MESG_RECOMMENDED_BUFFER_SIZE );

	EXPOSE_CONST( MESG_INVALID_ID );
	EXPOSE_CONST( MESG_EVENT_ID );

	EXPOSE_CONST( MESG_VERSION_ID );
	EXPOSE_CONST( MESG_RESPONSE_EVENT_ID );

	EXPOSE_CONST( MESG_UNASSIGN_CHANNEL_ID );
	EXPOSE_CONST( MESG_ASSIGN_CHANNEL_ID );
	EXPOSE_CONST( MESG_CHANNEL_MESG_PERIOD_ID );
	EXPOSE_CONST( MESG_CHANNEL_SEARCH_TIMEOUT_ID );
	EXPOSE_CONST( MESG_CHANNEL_RADIO_FREQ_ID );
	EXPOSE_CONST( MESG_NETWORK_KEY_ID );
	EXPOSE_CONST( MESG_RADIO_TX_POWER_ID );
	EXPOSE_CONST( MESG_RADIO_CW_MODE_ID );
	EXPOSE_CONST( MESG_SYSTEM_RESET_ID );
	EXPOSE_CONST( MESG_OPEN_CHANNEL_ID );
	EXPOSE_CONST( MESG_CLOSE_CHANNEL_ID );
	EXPOSE_CONST( MESG_REQUEST_ID );

	EXPOSE_CONST( MESG_BROADCAST_DATA_ID );
	EXPOSE_CONST( MESG_ACKNOWLEDGED_DATA_ID );
	EXPOSE_CONST( MESG_BURST_DATA_ID );

	EXPOSE_CONST( MESG_CHANNEL_ID_ID );
	EXPOSE_CONST( MESG_CHANNEL_STATUS_ID );
	EXPOSE_CONST( MESG_RADIO_CW_INIT_ID );
	EXPOSE_CONST( MESG_CAPABILITIES_ID );

	EXPOSE_CONST( MESG_STACKLIMIT_ID );

	EXPOSE_CONST( MESG_SCRIPT_DATA_ID );
	EXPOSE_CONST( MESG_SCRIPT_CMD_ID );

	EXPOSE_CONST( MESG_ID_LIST_ADD_ID );
	EXPOSE_CONST( MESG_CRYPTO_ID_LIST_ADD_ID );
	EXPOSE_CONST( MESG_ID_LIST_CONFIG_ID );
	EXPOSE_CONST( MESG_CRYPTO_ID_LIST_CONFIG_ID );
	EXPOSE_CONST( MESG_OPEN_RX_SCAN_ID );

	EXPOSE_CONST( MESG_EXT_CHANNEL_RADIO_FREQ_ID );
	EXPOSE_CONST( MESG_EXT_BROADCAST_DATA_ID );
	EXPOSE_CONST( MESG_EXT_ACKNOWLEDGED_DATA_ID );
	EXPOSE_CONST( MESG_EXT_BURST_DATA_ID );

	EXPOSE_CONST( MESG_CHANNEL_RADIO_TX_POWER_ID );
	EXPOSE_CONST( MESG_GET_SERIAL_NUM_ID );
	EXPOSE_CONST( MESG_GET_TEMP_CAL_ID );
	EXPOSE_CONST( MESG_SET_LP_SEARCH_TIMEOUT_ID );
	EXPOSE_CONST( MESG_SET_TX_SEARCH_ON_NEXT_ID );
	EXPOSE_CONST( MESG_SERIAL_NUM_SET_CHANNEL_ID_ID );
	EXPOSE_CONST( MESG_RX_EXT_MESGS_ENABLE_ID );
	EXPOSE_CONST( MESG_RADIO_CONFIG_ALWAYS_ID );
	EXPOSE_CONST( MESG_ENABLE_LED_FLASH_ID );
	EXPOSE_CONST( MESG_XTAL_ENABLE_ID );
	EXPOSE_CONST( MESG_ANTLIB_CONFIG_ID );
	EXPOSE_CONST( MESG_STARTUP_MESG_ID );
	EXPOSE_CONST( MESG_AUTO_FREQ_CONFIG_ID );
	EXPOSE_CONST( MESG_PROX_SEARCH_CONFIG_ID );

	EXPOSE_CONST( MESG_ADV_BURST_DATA_ID );
	EXPOSE_CONST( MESG_EVENT_BUFFERING_CONFIG_ID );

	EXPOSE_CONST( MESG_SET_SEARCH_CH_PRIORITY_ID );

	EXPOSE_CONST( MESG_HIGH_DUTY_SEARCH_MODE_ID );
	EXPOSE_CONST( MESG_CONFIG_ADV_BURST_ID );
	EXPOSE_CONST( MESG_EVENT_FILTER_CONFIG_ID );
	EXPOSE_CONST( MESG_SDU_CONFIG_ID );
	EXPOSE_CONST( MESG_SDU_SET_MASK_ID );
	EXPOSE_CONST( MESG_USER_CONFIG_PAGE_ID );
	EXPOSE_CONST( MESG_ENCRYPT_ENABLE_ID );
	EXPOSE_CONST( MESG_SET_CRYPTO_KEY_ID );
	EXPOSE_CONST( MESG_SET_CRYPTO_INFO_ID );
	EXPOSE_CONST( MESG_CUBE_CMD_ID );

	EXPOSE_CONST( MESG_ACTIVE_SEARCH_SHARING_ID );
	EXPOSE_CONST( MESG_NVM_CRYPTO_KEY_OPS_ID );

	EXPOSE_CONST( MESG_GET_PIN_DIODE_CONTROL_ID );
	EXPOSE_CONST( MESG_PIN_DIODE_CONTROL_ID );
	EXPOSE_CONST( MESG_FIT1_SET_AGC_ID );

	EXPOSE_CONST( MESG_FIT1_SET_EQUIP_STATE_ID );

	EXPOSE_CONST( MESG_SET_CHANNEL_INPUT_MASK_ID );
	EXPOSE_CONST( MESG_SET_CHANNEL_DATA_TYPE_ID );
	EXPOSE_CONST( MESG_READ_PINS_FOR_SECT_ID );
	EXPOSE_CONST( MESG_TIMER_SELECT_ID );
	EXPOSE_CONST( MESG_ATOD_SETTINGS_ID );
	EXPOSE_CONST( MESG_SET_SHARED_ADDRESS_ID );
	EXPOSE_CONST( MESG_ATOD_EXTERNAL_ENABLE_ID );
	EXPOSE_CONST( MESG_ATOD_PIN_SETUP_ID );
	EXPOSE_CONST( MESG_SETUP_ALARM_ID );
	EXPOSE_CONST( MESG_ALARM_VARIABLE_MODIFY_TEST_ID );
	EXPOSE_CONST( MESG_PARTIAL_RESET_ID );
	EXPOSE_CONST( MESG_OVERWRITE_TEMP_CAL_ID );
	EXPOSE_CONST( MESG_SERIAL_PASSTHRU_SETTINGS_ID );

	EXPOSE_CONST( MESG_BIST_ID );
	EXPOSE_CONST( MESG_UNLOCK_INTERFACE_ID );
	EXPOSE_CONST( MESG_SERIAL_ERROR_ID );
	EXPOSE_CONST( MESG_SET_ID_STRING_ID );

	EXPOSE_CONST( MESG_PORT_GET_IO_STATE_ID );
	EXPOSE_CONST( MESG_PORT_SET_IO_STATE_ID );

	EXPOSE_CONST( MESG_RSSI_ID );
	EXPOSE_CONST( MESG_RSSI_BROADCAST_DATA_ID );
	EXPOSE_CONST( MESG_RSSI_ACKNOWLEDGED_DATA_ID );
	EXPOSE_CONST( MESG_RSSI_BURST_DATA_ID );
	EXPOSE_CONST( MESG_RSSI_SEARCH_THRESHOLD_ID );
	EXPOSE_CONST( MESG_SLEEP_ID );
	EXPOSE_CONST( MESG_GET_GRMN_ESN_ID );
	EXPOSE_CONST( MESG_SET_USB_INFO_ID );

	EXPOSE_CONST( MESG_HCI_COMMAND_COMPLETE );

	EXPOSE_CONST( MESG_EXT_ID_0 );
	EXPOSE_CONST( MESG_EXT_ID_1 );
	EXPOSE_CONST( MESG_EXT_ID_2 );

	EXPOSE_CONST( MESG_EXT_RESPONSE_ID );

	EXPOSE_CONST( MESG_EXT_REQUEST_ID );

	EXPOSE_CONST( MESG_FS_INIT_MEMORY_ID );
	EXPOSE_CONST( MESG_FS_FORMAT_MEMORY_ID );
	EXPOSE_CONST( MESG_FS_GET_USED_SPACE_ID );
	EXPOSE_CONST( MESG_FS_GET_FREE_SPACE_ID );
	EXPOSE_CONST( MESG_FS_FIND_FILE_INDEX_ID );
	EXPOSE_CONST( MESG_FS_DIRECTORY_READ_ABSOLUTE_ID );
	EXPOSE_CONST( MESG_FS_DIRECTORY_READ_ENTRY_ID );
	EXPOSE_CONST( MESG_FS_DIRECTORY_SAVE_ID );
	EXPOSE_CONST( MESG_FS_DIRECTORY_GET_SIZE_ID );
	EXPOSE_CONST( MESG_FS_DIRECTORY_REBUILD_ID );
	EXPOSE_CONST( MESG_FS_FILE_CREATE_ID );
	EXPOSE_CONST( MESG_FS_FILE_OPEN_ID );
	EXPOSE_CONST( MESG_FS_FILE_DELETE_ID );
	EXPOSE_CONST( MESG_FS_FILE_CLOSE_ID );
	EXPOSE_CONST( MESG_FS_FILE_READ_ABSOLUTE_ID );
	EXPOSE_CONST( MESG_FS_FILE_READ_RELATIVE_ID );
	EXPOSE_CONST( MESG_FS_FILE_WRITE_ABSOLUTE_ID );
	EXPOSE_CONST( MESG_FS_FILE_WRITE_RELATIVE_ID );
	EXPOSE_CONST( MESG_FS_FILE_SET_SPECIFIC_FLAGS_ID );
	EXPOSE_CONST( MESG_FS_FILE_GET_SIZE_ID );
	EXPOSE_CONST( MESG_FS_FILE_GET_SPECIFIC_FILE_FLAGS_ID );
	EXPOSE_CONST( MESG_FS_FILE_GET_SIZE_IN_MEM_ID );
	EXPOSE_CONST( MESG_FS_DIRECTORY_READ_LOCK_ID );

	EXPOSE_CONST( MESG_FS_FILE_SET_GENERAL_FLAGS_ID );
	EXPOSE_CONST( MESG_FS_DIRECTORY_WRITE_ABSOLUTE_ID );

	EXPOSE_CONST( MESG_MEMDEV_EEPROM_INIT_ID );
	EXPOSE_CONST( MESG_MEMDEV_FLASH_INIT_ID );

	EXPOSE_CONST( MESG_FS_ANTFS_EVENT_ID );
	EXPOSE_CONST( MESG_FS_ANTFS_OPEN_ID );
	EXPOSE_CONST( MESG_FS_ANTFS_CLOSE_ID );
	EXPOSE_CONST( MESG_FS_ANTFS_CONFIG_BEACON_ID );
	EXPOSE_CONST( MESG_FS_ANTFS_SET_AUTH_STRING_ID );
	EXPOSE_CONST( MESG_FS_ANTFS_SET_BEACON_STATE_ID );
	EXPOSE_CONST( MESG_FS_ANTFS_PAIR_RESPONSE_ID );
	EXPOSE_CONST( MESG_FS_ANTFS_SET_LINK_FREQ_ID );
	EXPOSE_CONST( MESG_FS_ANTFS_SET_BEACON_TIMEOUT_ID );
	EXPOSE_CONST( MESG_FS_ANTFS_SET_PAIRING_TIMEOUT_ID );
	EXPOSE_CONST( MESG_FS_ANTFS_REMOTE_FILE_CREATE_EN_ID );
	EXPOSE_CONST( MESG_FS_ANTFS_GET_CMD_PIPE_ID );
	EXPOSE_CONST( MESG_FS_ANTFS_SET_CMD_PIPE_ID );
	EXPOSE_CONST( MESG_FS_SYSTEM_TIME_ID );
	EXPOSE_CONST( MESG_FS_ANTFS_SET_ANTFS_STATE_ID );

	EXPOSE_CONST( MESG_FS_CRYPTO_ADD_USER_KEY_INDEX_ID );
	EXPOSE_CONST( MESG_FS_CRYPTO_SET_USER_KEY_INDEX_ID );
	EXPOSE_CONST( MESG_FS_CRYPTO_SET_USER_KEY_VAL_ID );

	EXPOSE_CONST( MESG_FS_FIT_FILE_INTEGRITY_CHECK_ID );

	EXPOSE_CONST( MESG_INVALID_SIZE );

	EXPOSE_CONST( MESG_VERSION_SIZE );
	EXPOSE_CONST( MESG_RESPONSE_EVENT_SIZE );
	EXPOSE_CONST( MESG_CHANNEL_STATUS_SIZE );

	EXPOSE_CONST( MESG_UNASSIGN_CHANNEL_SIZE );
	EXPOSE_CONST( MESG_ASSIGN_CHANNEL_SIZE );
	EXPOSE_CONST( MESG_CHANNEL_ID_SIZE );
	EXPOSE_CONST( MESG_CHANNEL_MESG_PERIOD_SIZE );
	EXPOSE_CONST( MESG_CHANNEL_SEARCH_TIMEOUT_SIZE );
	EXPOSE_CONST( MESG_CHANNEL_RADIO_FREQ_SIZE );
	EXPOSE_CONST( MESG_CHANNEL_RADIO_TX_POWER_SIZE );
	EXPOSE_CONST( MESG_NETWORK_KEY_SIZE );
	EXPOSE_CONST( MESG_RADIO_TX_POWER_SIZE );
	EXPOSE_CONST( MESG_RADIO_CW_MODE_SIZE );
	EXPOSE_CONST( MESG_RADIO_CW_INIT_SIZE );
	EXPOSE_CONST( MESG_SYSTEM_RESET_SIZE );
	EXPOSE_CONST( MESG_OPEN_CHANNEL_SIZE );
	EXPOSE_CONST( MESG_CLOSE_CHANNEL_SIZE );
	EXPOSE_CONST( MESG_REQUEST_SIZE );
	EXPOSE_CONST( MESG_REQUEST_USER_NVM_SIZE );

	EXPOSE_CONST( MESG_CAPABILITIES_SIZE );
	EXPOSE_CONST( MESG_STACKLIMIT_SIZE );

	EXPOSE_CONST( MESG_SCRIPT_DATA_SIZE );
	EXPOSE_CONST( MESG_SCRIPT_CMD_SIZE );

	EXPOSE_CONST( MESG_ID_LIST_ADD_SIZE );
	EXPOSE_CONST( MESG_ID_LIST_CONFIG_SIZE );
	EXPOSE_CONST( MESG_OPEN_RX_SCAN_SIZE );
	EXPOSE_CONST( MESG_EXT_CHANNEL_RADIO_FREQ_SIZE );

	EXPOSE_CONST( MESG_RADIO_CONFIG_ALWAYS_SIZE );
	EXPOSE_CONST( MESG_RX_EXT_MESGS_ENABLE_SIZE );
	EXPOSE_CONST( MESG_SET_TX_SEARCH_ON_NEXT_SIZE );
	EXPOSE_CONST( MESG_SET_LP_SEARCH_TIMEOUT_SIZE );

	EXPOSE_CONST( MESG_SERIAL_NUM_SET_CHANNEL_ID_SIZE );
	EXPOSE_CONST( MESG_ENABLE_LED_FLASH_SIZE );
	EXPOSE_CONST( MESG_GET_SERIAL_NUM_SIZE );
	EXPOSE_CONST( MESG_GET_TEMP_CAL_SIZE );
	EXPOSE_CONST( MESG_CONFIG_ADV_BURST_SIZE );
	EXPOSE_CONST( MESG_CONFIG_ADV_BURST_SIZE_EXT );
	EXPOSE_CONST( MESG_ANTLIB_CONFIG_SIZE );
	EXPOSE_CONST( MESG_XTAL_ENABLE_SIZE );
	EXPOSE_CONST( MESG_STARTUP_MESG_SIZE );
	EXPOSE_CONST( MESG_AUTO_FREQ_CONFIG_SIZE );
	EXPOSE_CONST( MESG_PROX_SEARCH_CONFIG_SIZE );
	EXPOSE_CONST( MESG_EVENT_BUFFERING_CONFIG_SIZE );
	EXPOSE_CONST( MESG_EVENT_FILTER_CONFIG_SIZE );
	EXPOSE_CONST( MESG_HIGH_DUTY_SEARCH_MODE_SIZE );
	EXPOSE_CONST( MESG_SDU_CONFIG_SIZE );
	EXPOSE_CONST( MESG_SDU_SET_MASK_SIZE );

	EXPOSE_CONST( MESG_USER_CONFIG_PAGE_SIZE );

	EXPOSE_CONST( MESG_ACTIVE_SEARCH_SHARING_SIZE );

	EXPOSE_CONST( MESG_SET_SEARCH_CH_PRIORITY_SIZE );

	EXPOSE_CONST( MESG_ENCRYPT_ENABLE_SIZE );
	EXPOSE_CONST( MESG_SET_CRYPTO_KEY_SIZE );
	EXPOSE_CONST( MESG_SET_CRYPTO_ID_SIZE );
	EXPOSE_CONST( MESG_SET_CRYPTO_USER_INFO_SIZE );
	EXPOSE_CONST( MESG_SET_CRYPTO_RNG_SEED_SIZE );
	EXPOSE_CONST( MESG_NVM_CRYPTO_KEY_LOAD_SIZE );
	EXPOSE_CONST( MESG_NVM_CRYPTO_KEY_STORE_SIZE );
	EXPOSE_CONST( MESG_CRYPTO_ID_LIST_ADD_SIZE );
	EXPOSE_CONST( MESG_CRYPTO_ID_LIST_CONFIG_SIZE );

	EXPOSE_CONST( MESG_GET_PIN_DIODE_CONTROL_SIZE );
	EXPOSE_CONST( MESG_PIN_DIODE_CONTROL_ID_SIZE );
	EXPOSE_CONST( MESG_FIT1_SET_EQUIP_STATE_SIZE );
	EXPOSE_CONST( MESG_FIT1_SET_AGC_SIZE );

	EXPOSE_CONST( MESG_BIST_SIZE );
	EXPOSE_CONST( MESG_UNLOCK_INTERFACE_SIZE );
	EXPOSE_CONST( MESG_SET_SHARED_ADDRESS_SIZE );

	EXPOSE_CONST( MESG_GET_GRMN_ESN_SIZE );

	EXPOSE_CONST( MESG_PORT_SET_IO_STATE_SIZE );

	EXPOSE_CONST( MESG_SLEEP_SIZE );

	EXPOSE_CONST( MESG_EXT_DATA_SIZE );

	EXPOSE_CONST( MESG_RSSI_SIZE );
	EXPOSE_CONST( MESG_RSSI_DATA_SIZE );
	EXPOSE_CONST( MESG_RSSI_RESPONSE_SIZE );
	EXPOSE_CONST( MESG_RSSI_SEARCH_THRESHOLD_SIZE );

	EXPOSE_CONST( MESG_MEMDEV_EEPROM_INIT_SIZE );
	EXPOSE_CONST( MESG_FS_INIT_MEMORY_SIZE );
	EXPOSE_CONST( MESG_FS_FORMAT_MEMORY_SIZE );
	EXPOSE_CONST( MESG_FS_DIRECTORY_SAVE_SIZE );
	EXPOSE_CONST( MESG_FS_DIRECTORY_REBUILD_SIZE );
	EXPOSE_CONST( MESG_FS_FILE_DELETE_SIZE );
	EXPOSE_CONST( MESG_FS_FILE_CLOSE_SIZE );
	EXPOSE_CONST( MESG_FS_FILE_SET_SPECIFIC_FLAGS_SIZE );
	EXPOSE_CONST( MESG_FS_DIRECTORY_READ_LOCK_SIZE );
	EXPOSE_CONST( MESG_FS_SYSTEM_TIME_SIZE );
	EXPOSE_CONST( MESG_FS_CRYPTO_ADD_USER_KEY_INDEX_SIZE );
	EXPOSE_CONST( MESG_FS_CRYPTO_SET_USER_KEY_INDEX_SIZE );
	EXPOSE_CONST( MESG_FS_CRYPTO_SET_USER_KEY_VAL_SIZE );
	EXPOSE_CONST( MESG_FS_FIT_FILE_INTEGRITY_CHECK_SIZE );
	EXPOSE_CONST( MESG_FS_ANTFS_OPEN_SIZE );
	EXPOSE_CONST( MESG_FS_ANTFS_CLOSE_SIZE );
	EXPOSE_CONST( MESG_FS_ANTFS_CONFIG_BEACON_SIZE );
	EXPOSE_CONST( MESG_FS_ANTFS_SET_AUTH_STRING_SIZE );
	EXPOSE_CONST( MESG_FS_ANTFS_SET_BEACON_STATE_SIZE );
	EXPOSE_CONST( MESG_FS_ANTFS_PAIR_RESPONSE_SIZE );
	EXPOSE_CONST( MESG_FS_ANTFS_SET_LINK_FREQ_SIZE );
	EXPOSE_CONST( MESG_FS_ANTFS_SET_BEACON_TIMEOUT_SIZE );
	EXPOSE_CONST( MESG_FS_ANTFS_SET_PAIRING_TIMEOUT_SIZE );
	EXPOSE_CONST( MESG_FS_ANTFS_REMOTE_FILE_CREATE_EN_SIZE );
	EXPOSE_CONST( MESG_FS_GET_USED_SPACE_SIZE );
	EXPOSE_CONST( MESG_FS_GET_FREE_SPACE_SIZE );
	EXPOSE_CONST( MESG_FS_FIND_FILE_INDEX_SIZE );
	EXPOSE_CONST( MESG_FS_DIRECTORY_READ_ABSOLUTE_SIZE );
	EXPOSE_CONST( MESG_FS_DIRECTORY_READ_ENTRY_SIZE );
	EXPOSE_CONST( MESG_FS_DIRECTORY_GET_SIZE_SIZE );
	EXPOSE_CONST( MESG_FS_FILE_CREATE_SIZE );
	EXPOSE_CONST( MESG_FS_FILE_OPEN_SIZE );
	EXPOSE_CONST( MESG_FS_FILE_READ_ABSOLUTE_SIZE );
	EXPOSE_CONST( MESG_FS_FILE_READ_RELATIVE_SIZE );
	EXPOSE_CONST( MESG_FS_FILE_WRITE_ABSOLUTE_SIZE );
	EXPOSE_CONST( MESG_FS_FILE_WRITE_RELATIVE_SIZE );
	EXPOSE_CONST( MESG_FS_FILE_GET_SIZE_SIZE );
	EXPOSE_CONST( MESG_FS_FILE_GET_SIZE_IN_MEM_SIZE );
	EXPOSE_CONST( MESG_FS_FILE_GET_SPECIFIC_FILE_FLAGS_SIZE );
	EXPOSE_CONST( MESG_FS_SYSTEM_TIME_REQUEST_SIZE );
	EXPOSE_CONST( MESG_FS_ANTFS_GET_CMD_PIPE_SIZE );
	EXPOSE_CONST( MESG_FS_ANTFS_SET_CMD_PIPE_SIZE );
	EXPOSE_CONST( MESG_FS_REQUEST_RESPONSE_SIZE );
#undef EXPOSE_CONST

	rb_require( "ant/message" );
}


